apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-todo-ui-ingress"
spec:
  ingressClassName: {{ .Values.ui.ingress.ingressClass }} #nginx
  rules:
  - host: {{ .Values.ui.ingress.host}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "{{ .Release.Name }}-todo-ui"
            port: 
              number: {{ .Values.ui.servicePort }}
