apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-todo-get-tasks-api-ingress"
spec:
  ingressClassName: {{ .Values.getTask.ingress.ingressClass }}
  rules:
  - host: {{ .Values.getTask.ingress.host}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: "{{ .Release.Name }}-todo-get-tasks-api"
            port: 
              number: {{ .Values.getTask.servicePort }}
