apiVersion: v1
kind: Service
metadata:
  name: todo-get-task-api
spec:
  type: ClusterIP
  selector:
    app: todo-get-task-api
  ports:
    - port: {{ .Values.getTask.servicePort }}
      targetPort: {{ .Values.getTask.targetPort }}